---
- gather_facts: false
  hosts: localhost
  vars_files:
    - Server_Inventory_hosts.yml
  tasks:
  - name: Create a change ticket in SNOW 
    register: new_change_request
    snow_record:
      data:
        u_environment: "{{item.Environment}}"
        cmdb_ci: "{{item.CI}}"
        start_date: "{{item.Release_date}}"
        short_description: "{{item.Short_Description}}"
        
      instance: dev50141
      password: Welsnow321#
      state: present
      table: change_request
      username: admin
    with_items:
        - "{{ serverinventory }}"
#    register: new_change_request
#- debug: var=new_change_request.record.number
